-- partitioning answer
select FIRSTNAME,LASTNAME,GPA,ENROLLMENTDATE,MAJOR,avg(GPA) OVER(PARTITION BY MAJOR) AS AVG_GPA FROM Student;
select FIRSTNAME,LASTNAME,GPA,ENROLLMENTDATE,MAJOR,COUNT(GPA) OVER(PARTITION BY MAJOR) AS COUNT_GPA FROM Student;
select FIRSTNAME,LASTNAME,GPA,ENROLLMENTDATE,MAJOR,SUM(GPA) OVER(PARTITION BY MAJOR) AS SUM_GPA FROM Student;
select FIRSTNAME,LASTNAME,GPA,ENROLLMENTDATE,MAJOR,MAX(GPA) OVER(PARTITION BY MAJOR) AS MAX_GPA FROM Student;
select FIRSTNAME,LASTNAME,GPA,ENROLLMENTDATE,MAJOR,MIN(GPA) OVER(PARTITION BY MAJOR) AS MIN_GPA FROM Student;

-- overall answer
select FIRSTNAME,LASTNAME,GPA,ENROLLMENTDATE,MAJOR,avg(GPA) OVER() AS AVG_GPA FROM Student;
select FIRSTNAME,LASTNAME,GPA,ENROLLMENTDATE,MAJOR,COUNT(GPA) OVER() AS COUNT_GPA FROM Student;
select FIRSTNAME,LASTNAME,GPA,ENROLLMENTDATE,MAJOR,SUM(GPA) OVER() AS SUM_GPA FROM Student;
select FIRSTNAME,LASTNAME,GPA,ENROLLMENTDATE,MAJOR,MAX(GPA) OVER() AS MAX_GPA FROM Student;
select FIRSTNAME,LASTNAME,GPA,ENROLLMENTDATE,MAJOR,MIN(GPA) OVER() AS MIN_GPA FROM Student;